import { describe, expect, it } from "vitest";
import { normalizeForScreen, screensAsSelfHarm } from "./safetyScreen.js";

describe("screensAsSelfHarm", () => {
  it.each([
    "I want to kill myself",
    "i keep thinking about killing my self",
    "I've been cutting again and I don't know how to stop",
    "I wish I could go to sleep and never wake up",
    "I wish I wouldn’t wake up tomorrow",
    "Everyone would be better off without me",
    "I don't see the point in being alive anymore",
    "sometimes i think about just ending it all",
    "I just want to die",
    "honestly i wanna die",
    "I don't want to be alive",
    "I dont want to exist anymore",
    "There's no reason to live",
    "I've been feeling suicidal",
    "thinking about self-harm again",
    "I wish I was dead",
    "ne želim više živjeti",
    "ubit ću se",
    "želim umrijeti",
    "Ich will nicht mehr leben",
    "ich möchte sterben",
    "no quiero vivir",
    "quiero morirme",
    "jeg vil ikke leve mere",
    "jeg vil dø",
    "jeg vil ikke leve lenger",
    "de har det bedre uten meg",
    "jeg vil ta livet mitt",
    "je veux mourir",
    "je veux mourir demain",
    "j'ai envie d'en finir",
    "je n'ai plus envie de vivre",
    "ils seraient mieux sans moi",
    "je pense au suicide",
    "j'aimerais m'endormir et ne jamais me réveiller",
    "je voudrais ne plus jamais me réveiller",
    "je vais me tuer aujourd'hui",
    "quero morrer",
    "não quero mais viver",
    "eles estariam melhor sem mim",
    "vou me matar depois",
    "penso em suicídio",
    "voglio morire",
    "non voglio più vivere",
    "starebbero meglio senza di me",
    "voglio farmi del male",
    "ik wil niet meer leven",
    "ik wil dood",
    "ze zijn beter af zonder mij",
    "ik denk aan zelfmoord",
    "nie chcę już żyć",
    "chcę umrzeć",
    "chcę się zabić",
    "mam myśli samobójcze",
    "я не хочу больше жить",
    "хочу умереть",
    "думаю о самоубийстве",
    "всем будет лучше без меня",
    "хочу покончить с собой",
    "я не хочу більше жити",
    "хочу померти",
    "думаю про самогубство",
    "всім буде краще без мене",
    "ölmek istiyorum",
    "artık yaşamak istemiyorum",
    "ben de yaşamak istemiyorum",
    "intihar etmeyi düşünüyorum",
    "kendimi öldürmek istiyorum",
    "bensiz daha iyi olurlar",
    "aku ingin mati",
    "aku gak mau hidup lagi",
    "mereka lebih baik tanpaku",
    "aku mau bunuh diri",
    "jag vill inte leva längre",
    "jag vill dö",
    "de har det bättre utan mig",
    "jag tänker på självmord",
  ])("flags %s", (text) => {
    expect(screensAsSelfHarm([text])).toBe(true);
  });

  it.each([
    "This deadline is killing me, I have three reports due tomorrow",
    "I could murder a pizza right now but I'm on this stupid diet and I'm miserable",
    "I'm dying of embarrassment after tripping on stage at my graduation",
    "My boss is going to kill me when he finds out I lost the client",
    "I wanted to die when I tripped on stage",
    "I want to die of embarrassment",
    "I don't want to die alone",
    "I don't want to die, the scan results scare me",
    "I hurt myself at the gym and now I can't train",
    "I cut myself cooking and felt so stupid",
    "I don't want to live in this city anymore",
    "I don't want to live like this, the commute is destroying me",
    "I'd kill for a coffee after this meeting",
    "She killed it at the presentation and I felt useless",
    "I'm dead tired and still have to cook",
    "my mum died last week and the house is so quiet i can't stand being in it",
    "I'm cutting back on sugar and I'm miserable",
    "ne želim više živjeti ovdje",
    "ubit će me šef",
    "no quiero vivir aquí",
    "jeg vil ikke leve med det",
    "jeg vil ikke leve uten deg",
    "jeg vil ta livet mitt tilbake",
    "je veux mourir de rire",
    "ce boulot va me tuer",
    "je veux en finir avec ce projet",
    "je ne veux plus vivre ici",
    "tu es ma raison de vivre",
    "essaie de ne pas me réveiller demain",
    "j'aimerais ne plus me réveiller la nuit",
    "quero morrer de rir",
    "não quero viver aqui",
    "vou me matar de estudar",
    "cuidado para não acordar o bebê",
    "voglio morire dal ridere",
    "non voglio più vivere così",
    "mi ammazzo di lavoro",
    "ik wil niet meer leven in deze stad",
    "ik ga dood van de hitte",
    "nie chcę żyć w tym mieście",
    "chcę umrzeć ze śmiechu",
    "strzelił samobója w ostatniej minucie",
    "не хочу жить в этом городе",
    "я чуть не умерла от стыда",
    "не хочу жити в цьому місті",
    "burada yaşamak istemiyorum",
    "onunla yaşamak istemiyorum",
    "lebih baik tanpa gula",
    "jag vill inte leva med honom",
    "jag vill inte leva längre här",
    "jag vill dö av skratt",
  ])("leaves %s alone", (text) => {
    expect(screensAsSelfHarm([text])).toBe(false);
  });

  it("checks every piece of the user's own text", () => {
    expect(screensAsSelfHarm(["work has been rough", "honestly I want to end my life"])).toBe(true);
  });
});

describe("normalizeForScreen", () => {
  it("strips diacritics, punctuation, and curly apostrophes", () => {
    expect(normalizeForScreen("  Don’t — ŽELIM   umrijeti!! ")).toBe("don't zelim umrijeti");
  });

  it("reads Cyrillic й and ї as their bare letters", () => {
    expect(normalizeForScreen("Самоубийство, їм")).toBe("самоубииство ім");
  });
});
